# .github/workflows/build-windows-no-log.yml
name: Build rkdeveloptool for Windows (no-log)

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Install MSYS autotools (autoconf, automake, etc.)
        shell: powershell
        run: |
          $env:MSYSTEM = 'MSYS'
          msys2 -c "pacman -Sy --noconfirm --needed base-devel"

      - name: Install MINGW64 toolchain & libusb
        shell: powershell
        run: |
          $env:MSYSTEM = 'MINGW64'
          msys2 -c "pacman -Sy --noconfirm --needed mingw-w64-x86_64-gcc mingw-w64-x86_64-libusb"

      - name: Patch out auto-log folder creation
        shell: powershell
        run: |
          (Get-Content RKLog.cpp) `
            -replace 'CreateDirectory\("log", nullptr\);', '//CreateDirectory("log", nullptr);' `
          | Set-Content RKLog.cpp

      - name: Generate configure scripts (autoreconf)
        shell: powershell
        run: |
          $env:MSYSTEM = 'MSYS'
          msys2 -c "autoreconf -fi"

      - name: Configure for MinGW64
        shell: powershell
        run: |
          $env:MSYSTEM = 'MINGW64'
          msys2 -c "./configure --host=x86_64-w64-mingw32 --disable-dependency-tracking"

      - name: Build rkdeveloptool.exe
        shell: powershell
        run: |
          $env:MSYSTEM = 'MINGW64'
          msys2 -c "make -j$(nproc)"

      - name: Upload no-log artifact
        uses: actions/upload-artifact@v4
        with:
          name: rkdeveloptool-windows-no-log
          path: rkdeveloptool.exe
