# .github/workflows/build-windows-no-log.yml
name: Build rkdeveloptool for Windows (no-log)

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Install MSYS2 + dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: |
            base-devel
            mingw-w64-x86_64-gcc
          msystem: MSYS

      - name: Disable auto-log folder
        shell: powershell
        run: |
          $env:MSYSTEM = 'MSYS'
          msys2 -c "sed -i 's/CreateDirectory(\"log\", nullptr);/\\/\\/CreateDirectory(\"log\", nullptr);/' RKLog.cpp"

      - name: Generate build scripts
        shell: powershell
        run: |
          $env:MSYSTEM = 'MSYS'
          msys2 -c "autoreconf -fi"

      - name: Configure for MinGW64
        shell: powershell
        run: |
          $env:MSYSTEM = 'MINGW64'
          msys2 -c "./configure --host=x86_64-w64-mingw32 --disable-dependency-tracking"

      - name: Build
        shell: powershell
        run: |
          $env:MSYSTEM = 'MINGW64'
          msys2 -c "make -j\$(nproc)"

      - name: Upload patched rkdeveloptool.exe
        uses: actions/upload-artifact@v4
        with:
          name: rkdeveloptool-windows-no-log
          path: rkdeveloptool.exe
