# .github/workflows/build-windows-no-log.yml
name: Build rkdeveloptool for Windows (no-log)

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Install MSYS2 + toolchains
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: |
            base-devel
            mingw-w64-x86_64-gcc
          msystem: MSYS

      - name: Patch RKLog.cpp to disable logging
        shell: powershell
        run: |
          (Get-Content RKLog.cpp) `
            -replace 'CreateDirectory\("log", nullptr\);', '//CreateDirectory("log", nullptr);' `
          | Set-Content RKLog.cpp

      - name: Generate configure scripts (MSYS)
        shell: bash
        run: |
          export MSYSTEM=MSYS
          autoreconf -fi

      - name: Configure for MinGW64
        shell: bash
        run: |
          export MSYSTEM=MINGW64
          ./configure --host=x86_64-w64-mingw32 --disable-dependency-tracking

      - name: Build rkdeveloptool.exe
        shell: bash
        run: |
          export MSYSTEM=MINGW64
          make -j$(nproc)

      - name: Upload no-log Windows exe
        uses: actions/upload-artifact@v4
        with:
          name: rkdeveloptool-windows-no-log
          path: rkdeveloptool.exe
