# .github/workflows/build-windows-no-log.yml
name: Build rkdeveloptool for Windows (no-log)

on:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake libtool pkg-config make \
            gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64

      - name: Patch out auto-log directory
        run: |
          sed -i 's/CreateDirectory("log", nullptr);/\/\/CreateDirectory("log", nullptr);/' RKLog.cpp

      - name: Generate configure scripts
        run: autoreconf -fi

      - name: Configure for Windows (x86_64)
        run: |
          CC=x86_64-w64-mingw32-gcc \
          ./configure --host=x86_64-w64-mingw32 --disable-dependency-tracking

      - name: Build executable
        run: make -j$(nproc)

      - name: Gather `rkdeveloptool.exe`
        run: |
          # the build puts it in src/, so move it up:
          mv src/rkdeveloptool.exe .

      - name: Publish Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: rkdeveloptool-windows-no-log
          path: rkdeveloptool.exe
