# .github/workflows/build-windows-no-log.yml
name: Build rkdeveloptool for Windows (no-log)

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up MSYS2 with Autotools & MinGW64
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MSYS
          install: |
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-libusb
            mingw-w64-x86_64-pkg-config

      - name: Patch RKLog.cpp (disable CreateDirectory)
        shell: msys2 {0}
        env:
          MSYSTEM: MSYS
        run: |
          sed -i 's@CreateDirectory("log", nullptr);@//CreateDirectory("log", nullptr);@' RKLog.cpp

      - name: Regenerate configure scripts (MSYS)
        shell: msys2 {0}
        env:
          MSYSTEM: MSYS
        run: |
          autoreconf -fi

      - name: Configure for native Windows (MINGW64)
        shell: msys2 {0}
        env:
          MSYSTEM: MINGW64
          PKG_CONFIG_PATH: /mingw64/lib/pkgconfig
        run: |
          ./configure --host=x86_64-w64-mingw32 --disable-dependency-tracking

      - name: Build rkdeveloptool.exe (MINGW64)
        shell: msys2 {0}
        env:
          MSYSTEM: MINGW64
        run: |
          make -j$(nproc)

      - name: Upload no-log Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: rkdeveloptool-windows-no-log
          path: rkdeveloptool.exe
