# .github/workflows/build-windows-no-log.yml
name: Build rkdeveloptool for Windows (no-log, static)

on:
  push:
    branches:
      - main
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up MSYS2 with Autotools & MinGW64
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MSYS
          install: |
            autoconf
            automake
            libtool
            pkgconf
            make
            m4
            patch
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-libusb

      - name: Patch RKLog::Init and remove unused var
        shell: msys2 {0}
        env:
          MSYSTEM: MSYS
        run: |
          # Stub out entire RKLog::Init() so it does nothing
          sed -i '/void RKLog::Init()/,/^}/c\void RKLog::Init() {}' RKLog.cpp
          # Remove the unused variable that breaks -Werror
          sed -i '/char szProgramProcPath\[100\];/d' main.cpp

      - name: Regenerate Autotools scripts (MSYS)
        shell: msys2 {0}
        env:
          MSYSTEM: MSYS
        run: |
          autoreconf -fi

      - name: Configure & build static Windows exe (MINGW64)
        shell: msys2 {0}
        env:
          MSYSTEM: MINGW64
          PKG_CONFIG_PATH: /mingw64/lib/pkgconfig
          CXXFLAGS: "-static-libgcc -static-libstdc++"
          LDFLAGS: "-static"
        run: |
          ./configure --host=x86_64-w64-mingw32 --disable-dependency-tracking
          make -j$(nproc)

      - name: Upload standalone rkdeveloptool.exe
        uses: actions/upload-artifact@v4
        with:
          name: rkdeveloptool-windows-no-log-static
          path: rkdeveloptool.exe
